name: artway_web
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  background_json_parser: ^1.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  go_router: ^3.1.1
  http: ^0.13.4
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  simple_animations: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2

  

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/image/
    - assets/icon/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
